# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_auto_20170710_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='picture',
            field=models.FileField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
